#spring应用名称（微服务名称）
spring:
  application:
    name: user
  #选择application-peer1.yml作为配置文件 目前在application中已经指定
  profiles:
    active: peer1

#服务注册到eureka地址
eureka:
  client:
    #请求url指向Eureka服务治理中心
    service-url:
      defaultZone: http://localhost:2244/eureka,http://localhost:2245/eureka/
  #服务实例主机名称 （所在的服务器地址？）
  instance:
    hostname: 127.0.0.1

